In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("MagicBricks_NaviMumbai_raw.csv")
pd.set_option("display.max_columns", 30)
df.head()

,title,price,area,bhk,bathroom,furnishing,floor,transaction,society,posted_by
0,3 BHK Apartment for Sale in Maithili The Trell...,₹2.71 Cr,Carpet Area1077 sqft,NaN,Bathroom4,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
1,3 BHK Apartment for Sale in Ravriya Neelkanth ...,₹1.77 Cr,Carpet Area1745 sqft,NaN,Bathroom3,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
2,"3 BHK Apartment for Sale in Codename Citadel, ...",₹2.95 Cr,Carpet Area1110 sqft,NaN,Bathroom2,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
3,3 BHK Apartment for Sale in Pristine Bhaveshwa...,₹1.63 Cr,Super Area1795 sqft,NaN,Bathroom3,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
4,2 BHK Apartment for Sale in Gajra Bhoomi Seren...,₹1.06 Cr,Carpet Area523 sqft,NaN,Bathroom2,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN

# inspect the raw data

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        750 non-null    str
 1   price        750 non-null    str
 2   area         750 non-null    str
 3   bhk          0 non-null      float64
 4   bathroom     750 non-null    str
 5   furnishing   748 non-null    str
 6   floor        665 non-null    str
 7   transaction  750 non-null    str
 8   society      241 non-null    str
 9   posted_by    660 non-null    str
dtypes: float64(1), str(9)
memory usage: 58.7 KB

# check nulls

In [3]:
df.isnull().sum()

title            0
price            0
area             0
bhk            750
bathroom         0
furnishing       2
floor           85
transaction      0
society        509
posted_by       90
dtype: int64

# check duplicates

In [4]:
df.duplicated().sum()

np.int64(3)

In [5]:
df.drop_duplicates(subset=["title", "price", "area"], inplace=True)
df = df.reset_index(drop=True)
df.duplicated().sum()

np.int64(0)

# check price (text > number, Cr/Lac)

In [6]:
def parse_price(p):
    if pd.isna(p):
        return np.nan
    p = p.replace("₹", "").replace(",", "").strip()
    number = float(p.replace("Cr", "").replace("Lac", "").strip())
    if "Cr" in p:
        return number * 10000000     # 1 crore
    elif "Lac" in p:
        return number * 100000       # 1 lakh
    else:
        return number

df["price_inr"] = df["price"].apply(parse_price)
df[["price", "price_inr"]].head()

      price   price_inr
0  ₹2.71 Cr  27100000.0
1  ₹1.77 Cr  17700000.0
2  ₹2.95 Cr  29500000.0
3  ₹1.63 Cr  16300000.0
4  ₹1.06 Cr  10600000.0

# clean Area (split type + number)

In [7]:
df["area_type"] = df["area"].str.replace("Area", " ").str.split().str[0]
df["area_sqft"] = df["area"].str.replace("Carpet Area", "").str.replace("Super Area", "").str.replace("sqft", "").str.strip().astype(float)
df[["area", "area_type", "area_sqft"]].head()

                   area area_type  area_sqft
0  Carpet Area1077 sqft    Carpet     1077.0
1  Carpet Area1745 sqft    Carpet     1745.0
2  Carpet Area1110 sqft    Carpet     1110.0
3   Super Area1795 sqft     Super     1795.0
4   Carpet Area523 sqft    Carpet      523.0

# BHK from title

In [8]:
df["bhk"] = df["title"].str.split(" BHK").str[0].str.strip().astype(int)
df["bhk"].unique()

array([3, 2])

In [9]:
df["bhk"].head(10)

0    3
1    3
2    3
3    3
4    2
5    3
6    3
7    3
8    2
9    2
Name: bhk, dtype: int64

# Locality from title

In [10]:
df["locality"] = df["title"].str.split(" Navi Mumbai").str[0].str.split(",").str[-1].str.strip()
df["locality"].value_counts().head(15)

locality
Panvel            122
Kharghar          103
Ulwe               57
Taloja             38
Kamothe            37
New Panvel         31
Kopar Khairane     27
Nerul              25
Roadpali           24
Ghansoli           18
Sanpada            18
Airoli             14
Juinagar           10
Seawoods           10
Vashi               8
Name: count, dtype: int64

# strip labels from bathroom / furnishing / transaction

In [11]:
df["bathroom"] = df["bathroom"].str.replace("Bathroom", "").astype(int)
df["furnishing"] = df["furnishing"].str.replace("Furnishing", "")
df["transaction"] = df["transaction"].str.replace("Transaction", "")

print(df["bathroom"].unique())
print(df["furnishing"].unique())
print(df["transaction"].unique())

[4 3 2 1 5]
<StringArray>
['Unfurnished', 'Semi-Furnished', 'Furnished', nan]
Length: 4, dtype: str
<StringArray>
['New Property', 'Resale']
Length: 2, dtype: str

# split Floor into two columns

In [12]:
df["floor_no"] = df["floor"].str.replace("Floor", "").str.split(" out of ").str[0]
df["total_floors"] = df["floor"].str.split(" out of ").str[1]

df["floor_no"] = pd.to_numeric(df["floor_no"], errors="coerce")
df["total_floors"] = pd.to_numeric(df["total_floors"], errors="coerce")

# ADD THESE 3 LINES HERE  ← convert float to nullable Int
df["floor_no"] = df["floor_no"].astype("Int64")
df["total_floors"] = df["total_floors"].astype("Int64")
df[["floor", "floor_no", "total_floors"]].head()

  floor  floor_no  total_floors
0   NaN      <NA>          <NA>
1   NaN      <NA>          <NA>
2   NaN      <NA>          <NA>
3   NaN      <NA>          <NA>
4   NaN      <NA>          <NA>

# split posted_by into type + name

In [13]:
df["posted_by_type"] = df["posted_by"].str.split(":").str[0].str.strip()
df["posted_by_name"] = df["posted_by"].str.split(":").str[-1].str.strip()
df["posted_by_type"].unique()

array([nan, 'Builder', 'Agent', 'Owner'], dtype=object)

In [14]:
df.isnull().sum()

title               0
price               0
area                0
bhk                 0
bathroom            0
furnishing          2
floor              80
transaction         0
society           491
posted_by          85
price_inr           0
area_type           0
area_sqft           0
locality            0
floor_no          100
total_floors       80
posted_by_type     85
posted_by_name     85
dtype: int64

# fill missing values (text = "Unknown", like class)

In [15]:
df["society"] = df["society"].fillna("Unknown")
df["posted_by_type"] = df["posted_by_type"].fillna("Unknown")
df["posted_by_name"] = df["posted_by_name"].fillna("Unknown")
df["furnishing"] = df["furnishing"].fillna("Unknown")

df.isnull().sum()

title               0
price               0
area                0
bhk                 0
bathroom            0
furnishing          0
floor              80
transaction         0
society             0
posted_by          85
price_inr           0
area_type           0
area_sqft           0
locality            0
floor_no          100
total_floors       80
posted_by_type      0
posted_by_name      0
dtype: int64

# price per sqft (new column)

In [16]:
df["price_per_sqft"] = (df["price_inr"] / df["area_sqft"]).round(0)
df[["locality", "price_inr", "area_sqft", "price_per_sqft"]].head()

             locality   price_inr  area_sqft  price_per_sqft
0      Kopar Khairane  27100000.0     1077.0         25162.0
1            Kharghar  17700000.0     1745.0         10143.0
2            Juinagar  29500000.0     1110.0         26577.0
3                Ulwe  16300000.0     1795.0          9081.0
4  Sector 37 Kharghar  10600000.0      523.0         20268.0

# EDA: category price band using apply (like your age_category)

In [17]:
def price_band(price):
    if price <= 5000000:          # up to 50 Lac
        return "Budget"
    elif price <= 10000000:       # 50 Lac - 1 Cr
        return "Mid"
    elif price <= 20000000:       # 1 - 2 Cr
        return "Premium"
    else:
        return "Luxury"

df["price_band"] = df["price_inr"].apply(price_band)
df["price_band"].value_counts()

price_band
Mid        283
Premium    269
Luxury      99
Budget      74
Name: count, dtype: int64

# EDA: groupby (locality wise avg price per sqft)

In [18]:
df.groupby("locality")["price_per_sqft"].mean().sort_values(ascending=False).head(10)

locality
Sector 16A Dharshana Society                      61728.0
Sector 5 Sanpada                                  54167.0
3 BHK  House for Sale in Sector 8B CBD Belapur    44233.0
3 BHK Apartment for Sale in Sector 6 Ghansoli     39111.0
Sector 15 CBD Belapur                             39062.0
Sector 19 Sanpada                                 36959.0
Nerul East                                        35833.0
Seawoods                                          35442.8
Juhu Village                                      32857.0
3 BHK Villa for Sale in Nerul                     31792.0
Name: price_per_sqft, dtype: float64

# EDA: groupby (BHK wise avg price)

In [19]:
df.groupby("bhk")["price_inr"].mean().sort_values(ascending=False)

bhk
3    2.427299e+07
2    9.973575e+06
Name: price_inr, dtype: float64

# EDA: pivot table (furnishing vs transaction count)

In [20]:
pd.pivot_table(
    df,
    values="price_inr",
    index="furnishing",
    columns="transaction",
    aggfunc="count"
)

transaction     New Property  Resale
furnishing
Furnished                NaN    81.0
Semi-Furnished          14.0   160.0
Unfurnished            115.0   353.0
Unknown                  NaN     2.0

In [21]:
df["posted_by_name"] = df["posted_by_name"].str.strip().str.title()
df["posted_by_name"].head(10)

0    Unknown
1    Unknown
2    Unknown
3    Unknown
4    Unknown
5    Unknown
6    Unknown
7    Unknown
8    Unknown
9    Unknown
Name: posted_by_name, dtype: object

In [22]:
df["society"] = df["society"].str.strip().str.title()

In [23]:
df

,title,price,area,bhk,bathroom,furnishing,floor,transaction,society,posted_by,price_inr,area_type,area_sqft,locality,floor_no,total_floors,posted_by_type,posted_by_name,price_per_sqft,price_band
0,3 BHK Apartment for Sale in Maithili The Trell...,₹2.71 Cr,Carpet Area1077 sqft,3,4,Unfurnished,NaN,New Property,Unknown,NaN,27100000.0,Carpet,1077.0,Kopar Khairane,<NA>,<NA>,Unknown,Unknown,25162.0,Luxury
1,3 BHK Apartment for Sale in Ravriya Neelkanth ...,₹1.77 Cr,Carpet Area1745 sqft,3,3,Unfurnished,NaN,New Property,Unknown,NaN,17700000.0,Carpet,1745.0,Kharghar,<NA>,<NA>,Unknown,Unknown,10143.0,Premium
2,"3 BHK Apartment for Sale in Codename Citadel, ...",₹2.95 Cr,Carpet Area1110 sqft,3,2,Unfurnished,NaN,New Property,Unknown,NaN,29500000.0,Carpet,1110.0,Juinagar,<NA>,<NA>,Unknown,Unknown,26577.0,Luxury
3,3 BHK Apartment for Sale in Pristine Bhaveshwa...,₹1.63 Cr,Super Area1795 sqft,3,3,Unfurnished,NaN,New Property,Unknown,NaN,16300000.0,Super,1795.0,Ulwe,<NA>,<NA>,Unknown,Unknown,9081.0,Premium
4,2 BHK Apartment for Sale in Gajra Bhoomi Seren...,₹1.06 Cr,Carpet Area523 sqft,2,2,Unfurnished,NaN,New Property,Unknown,NaN,10600000.0,Carpet,523.0,Sector 37 Kharghar,<NA>,<NA>,Unknown,Unknown,20268.0,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,"3 BHK Apartment for Sale in Ambe Prerna, Ghans...",₹1.20 Cr,Carpet Area720 sqft,3,2,Semi-Furnished,Floor5 out of 7,Resale,Unknown,Owner: Rajan Singh,12000000.0,Carpet,720.0,Ghansoli,5,7,Owner,Rajan Singh,16667.0,Premium
721,"2 BHK Apartment for Sale in Mamta Residency, T...",₹60 Lac,Carpet Area948 sqft,2,2,Unfurnished,Floor1 out of 7,Resale,Unknown,Owner: Rajpal Singh Bajwa,6000000.0,Carpet,948.0,Taloja,1,7,Owner,Rajpal Singh Bajwa,6329.0,Mid
722,"2 BHK Apartment for Sale in Mamta Residency, T...",₹57 Lac,Carpet Area778 sqft,2,2,Unfurnished,Floor1 out of 7,Resale,Unknown,Owner: Rajnish Patel,5700000.0,Carpet,778.0,Taloja,1,7,Owner,Rajnish Patel,7326.0,Mid
723,3 BHK Apartment for Sale in Babas Pearl Height...,₹1.30 Cr,Carpet Area1152 sqft,3,3,Unfurnished,Floor1 out of 13,Resale,Unknown,Owner: RAJKUMAR GOEL,13000000.0,Carpet,1152.0,Kamothe,1,13,Owner,Rajkumar Goel,11285.0,Premium
724,3 BHK Apartment for Sale in Babas Pearl Height...,₹1.10 Cr,Carpet Area664 sqft,3,3,Unfurnished,Floor11 out of 13,Resale,Unknown,Owner: Rajkumar Dhingra,11000000.0,Carpet,664.0,Kamothe,11,13,Owner,Rajkumar Dhingra,16566.0,Premium

In [24]:
df.info()
df.to_csv("MagicBricks_NaviMumbai_clean.csv", index=False, encoding="utf-8-sig")

<class 'pandas.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           725 non-null    str
 1   price           725 non-null    str
 2   area            725 non-null    str
 3   bhk             725 non-null    int64
 4   bathroom        725 non-null    int64
 5   furnishing      725 non-null    str
 6   floor           645 non-null    str
 7   transaction     725 non-null    str
 8   society         725 non-null    str
 9   posted_by       640 non-null    str
 10  price_inr       725 non-null    float64
 11  area_type       725 non-null    object
 12  area_sqft       725 non-null    float64
 13  locality        725 non-null    object
 14  floor_no        625 non-null    Int64
 15  total_floors    645 non-null    Int64
 16  posted_by_type  725 non-null    object
 17  posted_by_name  725 non-null    object
 18  price_per_sqft  725 non-null    float64
 19  price_band      725 non-null    str
dtypes: Int64(2), float64(3), int64(2), object(4), str(9)
memory usage: 114.8+ KB

In [27]:
%pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: pymysql in C:\Users\Mitali Padave\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.0)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Mitali Padave\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.52-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   --------- ------------------------------ 0.5/2.2 MB 123.5 kB/s eta 0:00:14
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.2 MB 129.6 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.2 MB 147.3 kB/s eta 0:00:08
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.2 MB 160.2 kB/s eta 0:00:06
   ----------------------------- ---------- 1.6/2.2 MB 156.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.2 MB 156.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.2 MB 156.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.2 MB 156.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.2 MB 156.9 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.2 MB 166.5 kB/s eta 0:00:02
   -------------------------------------- - 2.1/2.2 MB 155.0 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 155.0 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 154.5 kB/s  0:00:12
Downloading greenlet-3.5.5-cp314-cp314-win_amd64.whl (327 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.5 sqlalchemy-2.0.52
Note: you may need to restart the kernel to use updated packages.

In [29]:
# import pandas as pd
from sqlalchemy import create_engine

clean = pd.read_csv("MagicBricks_NaviMumbai_clean.csv")
engine = create_engine("mysql+pymysql://root:YOUR_PASSWORD@localhost/magicbricks")
clean.to_sql("properties_raw", engine, if_exists="replace", index=False)
print("rows loaded:", len(clean))

rows loaded: 725